//Even Fibonacci numbers
//Problem 2
//----------

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

//Solution
//---------

public class Test {
    public static void main(String[] args) {
        int sum = 0, fib1 = 0, fib2 = 1, num = 0, evensum = 0;
        
        while ( fib2 <= 4000000 )
        {
           num = fib1 + fib2;
           if ( num%2 == 0 )
           {
               evensum = evensum + num;
           }
           fib1 = fib2;
           fib2 = num;
           sum = sum + num;
        }
        System.out.print(evensum);        
    }
}
